// Obsidian vault writer — structured documentation to knowledge base
export interface ObsidianNote {
  path: string;          // vault-relative path
  content: string;       // markdown body
  tags: string[];        // obsidian tags
  frontmatter: Record<string, string>;
}

export async function writeObsidianNote(note: ObsidianNote): Promise<boolean> {
  // In production, calls mcp__obsidian__* tools to write to the vault
  console.log(`[Obsidian] Would write: ${note.path}`);
  return true;
}

export function buildTechnicalNote(
  project: string,
  branch: string,
  endpoints: string[],
  serializers: string[],
  migrations: string[],
): ObsidianNote {
  const content = [
    `# ${branch} — Technical Notes`,
    "",
    "## Endpoints touched",
    ...endpoints.map((e) => `- ${e}`),
    "",
    "## Serializers",
    ...serializers.map((s) => `- ${s}`),
    "",
    "## Migrations",
    ...(migrations.length > 0 ? migrations.map((m) => `- ${m}`) : ["- None"]),
    "",
    "---",
    `*Generated by agent-smith*`,
  ].join("\n");

  return {
    path: `${project}/docs/backend/${branch}.md`,
    content,
    tags: ["backend", "api", "technical"],
    frontmatter: {
      project,
      branch,
      type: "technical-notes",
    },
  };
}

export function buildUserGuideNote(
  project: string,
  flowName: string,
  roles: string[],
  steps: string[],
  screenshots: string[],
  roleDifferences: string,
): ObsidianNote {
  const content = [
    `# ${flowName}`,
    "",
    `> Who can do this: ${roles.join(" · ")}`,
    "",
    "## What this is for",
    "",
    "## Step by step",
    ...steps.flatMap((step, i) => [
      `${i + 1}. ${step}`,
      screenshots[i] ? `![](${screenshots[i]})` : "",
      "",
    ]),
    "## Differences by role",
    roleDifferences,
    "",
    "## Things to know",
    "",
    "---",
    `*Generated by agent-smith*`,
  ].join("\n");

  return {
    path: `${project}/docs/user-guide/${flowName.toLowerCase().replace(/\s+/g, "-")}.md`,
    content,
    tags: ["user-guide", flowName.toLowerCase()],
    frontmatter: {
      project,
      type: "user-guide",
      roles: roles.join(", "),
    },
  };
}
