// A8 — CI/CD first-class (scoped). agent-smith is a scaffolder, not a deploy platform: it
// GENERATES a CI workflow wired to the detected stack's REAL commands (from C2's authority) and
// provides post-PR verification skills — it does NOT own ephemeral envs / canary / rollback.
//
// The workflow is written to .github/workflows/agent-smith-ci.yml (a distinct name) so it never
// clobbers a project's existing CI.
import path from "node:path";
import fs from "fs-extra";
import type { TemplateVariables } from "../shared/types.js";

const NONE = new Set(["", "none", "unknown"]);
const real = (cmd: string | undefined): string | null => (cmd && !NONE.has(cmd.trim().toLowerCase()) ? cmd.trim() : null);

function stepsFor(label: string, cmds: Array<string | null>): string[] {
  const lines: string[] = [];
  for (const c of cmds) {
    if (!c) continue;
    lines.push(`      - name: ${label} — ${c.split(/\s+/)[0]}`);
    lines.push(`        run: ${c}`);
  }
  return lines;
}

/**
 * Generate a GitHub Actions workflow from the detected stack's real commands. Returns null when
 * nothing is determinable (no honest steps to run) so the caller can skip writing a useless file.
 */
export function generateCIWorkflow(vars: TemplateVariables): string | null {
  const backend = stepsFor("backend", [
    real(vars.BACKEND_LINT_CMD), real(vars.BACKEND_TYPE_CHECK_CMD), real(vars.BACKEND_TEST_CMD),
  ]);
  const frontend = stepsFor("frontend", [
    real(vars.FRONTEND_LINT_CMD), real(vars.FRONTEND_TYPE_CHECK_CMD), real(vars.FRONTEND_TEST_CMD),
  ]);
  if (backend.length === 0 && frontend.length === 0) return null;

  const jobs: string[] = [];
  if (backend.length > 0) {
    jobs.push(
      "  backend:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      ...backend,
    );
  }
  if (frontend.length > 0) {
    jobs.push(
      "  frontend:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      ...frontend,
    );
  }

  return [
    "# Generated by agent-smith (A8) — stack-aware CI using the project's REAL commands.",
    "# Tune freely; agent-smith only seeds this. It never clobbers your other workflows.",
    "name: agent-smith CI",
    "on:",
    "  push: { branches: [main] }",
    "  pull_request: {}",
    "jobs:",
    ...jobs,
    "",
  ].join("\n");
}

/** Write the generated workflow to .github/workflows/agent-smith-ci.yml (non-clobbering name). */
export async function scaffoldCI(targetDir: string, vars: TemplateVariables, dryRun = false): Promise<boolean> {
  const yml = generateCIWorkflow(vars);
  if (!yml) return false; // nothing honest to run → write nothing
  const dest = path.join(targetDir, ".github", "workflows", "agent-smith-ci.yml");
  if (dryRun) {
    console.log(`  Would write: ${dest}`);
    return true;
  }
  await fs.ensureDir(path.dirname(dest));
  await fs.writeFile(dest, yml, "utf-8");
  return true;
}
