/**
 * llm-step — LLM skill generation and skills report rendering.
 * Groups Step 13 (final) of initCommand.
 */
import chalk from "chalk";
import ora from "ora";
import { generateSkills, GENERATED_SKILLS } from "../../adapt/llm-skills.js";
import { writeMarker } from "../../adapt/skill-gen-marker.js";
import { renderSkillsReport } from "../skills-report.js";

interface LlmStepOptions {
  targetDir: string;
  agentSmithVersion: string;
  stackLabel: string;
  dryRun?: boolean;
  llm?: boolean;
  regenSkills?: boolean;
}

/** Runs LLM skill generation and writes the reproducibility marker. Best-effort — never blocks. */
export async function runLlmStep(opts: LlmStepOptions): Promise<void> {
  const { targetDir, agentSmithVersion, stackLabel, dryRun, llm, regenSkills } = opts;

  if (llm === false || dryRun) return;

  const skillGenSpinner = ora("Generating skills with Claude (live project, MCP enabled)...").start();
  const result = generateSkills(targetDir, {
    useProjectMcp: true,
    suppressHooks: true,
    regen: regenSkills,
  });

  if (result.ran) {
    writeMarker(targetDir, {
      generatedAt: new Date().toISOString(),
      stack: stackLabel,
      skills: GENERATED_SKILLS,
      promptHash: result.promptHash,
      agentSmithVersion,
    });
    skillGenSpinner.succeed("Skills generated by Claude");
    if (result.report) {
      renderSkillsReport(result.report);
    } else if (result.summary) {
      console.log(chalk.gray(`  ${result.summary}`));
    }
  } else {
    skillGenSpinner.warn(`LLM skill generation skipped (${result.reason}); using template-customized skills`);
  }
}
