// Sentrux installer — scaffolds the architecture quality gate into a target repo.
//
// agent-smith's `init` previously only PROBED sentrux to seed threshold values; it never
// actually wrote sentrux config into the target project. This module is the missing
// scaffolder: it creates `.sentrux/` with a `rules.toml` (constraints) and a starter
// `baseline.json` (the regression-check reference sentrux's gate compares against).
//
// Both files are parameterised by the SENTRUX_* template variables rather than hardcoded,
// mirroring the shape of this repo's own .sentrux/ directory.
import path from "node:path";
import fs from "fs-extra";
import type { TemplateVariables } from "../shared/types.js";

export interface SentruxInstallResult {
  /** True when this call wrote the config (a fresh scaffold). */
  installed: boolean;
  /** Absolute path to the `.sentrux/` directory, or null if nothing was written and none exists. */
  configPath: string | null;
  /** True when an existing config was found (or a benign error) and we left it untouched. */
  skipped: boolean;
  /** Human-readable explanation when installed is false. */
  reason?: string;
}

/**
 * Build the `.sentrux/rules.toml` body from the probed/interview template variables.
 *
 * - SENTRUX_MAX_CYCLES: numeric string → enforced; "" / "unknown" → commented out (advisory).
 * - SENTRUX_MAX_CC: max cyclomatic complexity threshold (default "25").
 * - SENTRUX_MAX_COUPLING: coupling grade (default "C").
 * - SENTRUX_LAYERS / SENTRUX_BOUNDARIES: pre-serialized TOML blocks injected verbatim.
 *
 * This mirrors `writeSentruxRules` in src/adapt/architecture-writer.ts so installs produce
 * the same file shape regardless of which path created it.
 */
function buildRulesToml(vars: TemplateVariables): string {
  const cyclesRaw = vars.SENTRUX_MAX_CYCLES?.trim() ?? "";
  const hasProbe = cyclesRaw !== "" && cyclesRaw !== "unknown";

  const cyclesLine = hasProbe
    ? `max_cycles = ${cyclesRaw}`
    : "# max_cycles = <not-probed>  # WARNING: check_rules is advisory until you run: sentrux scan . and re-init";

  const maxCC = vars.SENTRUX_MAX_CC?.trim() || "25";
  const maxCoupling = vars.SENTRUX_MAX_COUPLING?.trim() || "C";
  const layers = vars.SENTRUX_LAYERS?.trim() || "";
  const boundaries = vars.SENTRUX_BOUNDARIES?.trim() || "";

  const lines: string[] = [
    "# .sentrux/rules.toml — generated by agent-smith",
    "# Edit to tighten thresholds as technical debt is reduced.",
    "",
    "[constraints]",
    cyclesLine,
    `max_coupling = "${maxCoupling}"`,
    `max_cc = ${maxCC}`,
    "no_god_files = true",
  ];

  if (layers) lines.push("", layers);
  if (boundaries) lines.push("", boundaries);
  lines.push("");

  return lines.join("\n");
}

/**
 * Build a starter `.sentrux/baseline.json`. sentrux's `gate` command compares the working
 * tree against this baseline to detect structural regression. We seed it from the probed
 * cycle count (via SENTRUX_MAX_CYCLES) so the first gate run has a meaningful reference;
 * sentrux will overwrite/ratchet it once it runs a real scan.
 */
function buildBaseline(vars: TemplateVariables): Record<string, unknown> {
  const cyclesRaw = vars.SENTRUX_MAX_CYCLES?.trim() ?? "";
  const cycleCount = /^\d+$/.test(cyclesRaw) ? Number(cyclesRaw) : 0;

  return {
    timestamp: Date.now() / 1000,
    quality_signal: 0,
    coupling_score: 0,
    cycle_count: cycleCount,
    god_file_count: 0,
    hotspot_count: 0,
    complex_fn_count: 0,
    max_depth: 0,
    total_import_edges: 0,
    cross_module_edges: 0,
  };
}

/**
 * Scaffold sentrux config into `cwd`.
 *
 * Idempotent and non-destructive: if a `.sentrux/` config already exists (rules.toml or
 * baseline.json present), the existing config is preserved and the call is reported as
 * skipped. Never throws on a benign condition — failures are returned as a skipped result
 * with a reason.
 */
export async function installSentrux(
  cwd: string,
  templateVars: TemplateVariables,
): Promise<SentruxInstallResult> {
  const sentruxDir = path.join(cwd, ".sentrux");
  const rulesPath = path.join(sentruxDir, "rules.toml");
  const baselinePath = path.join(sentruxDir, "baseline.json");

  try {
    // Do not overwrite an existing configuration.
    const alreadyConfigured =
      (await fs.pathExists(rulesPath)) || (await fs.pathExists(baselinePath));
    if (alreadyConfigured) {
      return {
        installed: false,
        configPath: sentruxDir,
        skipped: true,
        reason: "already configured",
      };
    }

    await fs.ensureDir(sentruxDir);
    await fs.writeFile(rulesPath, buildRulesToml(templateVars), "utf-8");
    await fs.writeJson(baselinePath, buildBaseline(templateVars), { spaces: 2 });

    return { installed: true, configPath: sentruxDir, skipped: false };
  } catch (err) {
    return {
      installed: false,
      configPath: null,
      skipped: true,
      reason: err instanceof Error ? err.message : String(err),
    };
  }
}
