// Architecture writer — generates architecture docs from detected patterns
import path from "node:path";
import fs from "fs-extra";
import type { TemplateVariables, DetectedProject } from "../shared/types.js";
import { isClaudeAvailable } from "../analyze/claude-runner.js";
import { generateArchitectureDoc } from "./llm-architecture.js";

/**
 * Write .sentrux/rules.toml seeded from a live probe.
 *
 * - SENTRUX_MAX_CYCLES: numeric string or "unknown"/"" → if empty/unknown, comment it out
 *   and add a warning that check_rules is advisory until re-probed.
 * - SENTRUX_MAX_CC: max cyclomatic complexity, e.g. "15".
 * - SENTRUX_MAX_COUPLING: coupling grade, e.g. "B".
 * - SENTRUX_LAYERS / SENTRUX_BOUNDARIES: pre-serialized TOML blocks injected verbatim.
 */
export async function writeSentruxRules(
  targetDir: string,
  vars: TemplateVariables,
  dryRun: boolean = false,
): Promise<void> {
  const sentruxDir = path.join(targetDir, ".sentrux");
  const rulesPath = path.join(sentruxDir, "rules.toml");

  if (!dryRun) {
    fs.ensureDirSync(sentruxDir);
  }

  const cyclesRaw = vars.SENTRUX_MAX_CYCLES?.trim();
  const hasProbe = cyclesRaw !== "" && cyclesRaw !== "unknown";

  const cyclesLine = hasProbe
    ? `max_cycles = ${cyclesRaw}`
    : `# max_cycles = <not-probed>  # WARNING: check_rules is advisory until you run: sentrux scan . and re-init`;

  const maxCC = vars.SENTRUX_MAX_CC?.trim() || "25";
  const maxCoupling = vars.SENTRUX_MAX_COUPLING?.trim() || "C";

  const layers = vars.SENTRUX_LAYERS?.trim() || "";
  const boundaries = vars.SENTRUX_BOUNDARIES?.trim() || "";

  const lines: string[] = [
    "# .sentrux/rules.toml — generated by agent-smith",
    "# Edit to tighten thresholds as technical debt is reduced.",
    "",
    "[constraints]",
    cyclesLine,
    `max_coupling = "${maxCoupling}"`,
    `max_cc = ${maxCC}`,
    "no_god_files = true",
  ];

  if (layers) {
    lines.push("", layers);
  }

  if (boundaries) {
    lines.push("", boundaries);
  }

  lines.push("");

  const content = lines.join("\n");

  if (dryRun) {
    console.log(`  Would write: ${rulesPath}`);
    console.log(content
      .split("\n")
      .map((l) => `    ${l}`)
      .join("\n"));
  } else {
    await fs.writeFile(rulesPath, content, "utf-8");
  }
}

export interface WriteArchitectureOptions {
  /** When true (default) and the `claude` CLI is present, author docs with the LLM
   *  grounded in the real repo; otherwise use the deterministic templates. */
  useLlm?: boolean;
  /** Detected project — required for LLM grounding; templates work without it. */
  project?: DetectedProject | null;
  /** Callback for progress messages (e.g. spinner text). */
  onProgress?: (message: string) => void;
}

export async function writeArchitectureDocs(
  targetDir: string,
  vars: TemplateVariables,
  dryRun: boolean = false,
  opts: WriteArchitectureOptions = {},
): Promise<void> {
  const archDir = path.join(targetDir, "docs", "architecture");
  if (!dryRun) {
    fs.ensureDirSync(archDir);
  }

  const llmEnabled = (opts.useLlm ?? true) && !dryRun && !!opts.project && isClaudeAvailable();

  // Backend: prefer LLM-authored (grounded in real code), fall back to template.
  let backendDoc = generateBackendArchitecture(vars);
  if (llmEnabled) {
    opts.onProgress?.("Generating backend architecture with Claude...");
    const llmDoc = generateArchitectureDoc("backend", targetDir, opts.project!, backendDoc);
    if (llmDoc) backendDoc = llmDoc;
  }
  const backendPath = path.join(archDir, "backend-architecture.md");
  if (dryRun) {
    console.log(`  Would write: ${backendPath}`);
  } else {
    await fs.writeFile(backendPath, backendDoc, "utf-8");
  }

  // Frontend: same pattern.
  let frontendDoc = generateFrontendArchitecture(vars);
  if (llmEnabled) {
    opts.onProgress?.("Generating frontend architecture with Claude...");
    const llmDoc = generateArchitectureDoc("frontend", targetDir, opts.project!, frontendDoc);
    if (llmDoc) frontendDoc = llmDoc;
  }
  const frontendPath = path.join(archDir, "frontend-architecture.md");
  if (dryRun) {
    console.log(`  Would write: ${frontendPath}`);
  } else {
    await fs.writeFile(frontendPath, frontendDoc, "utf-8");
  }

  // MCP tools guide — a deterministic, binding reference for correct MCP usage
  // (esp. Serena, whose exact tool names + name-path syntax are easy to get wrong).
  const mcpPath = path.join(archDir, "mcp-tools.md");
  if (dryRun) {
    console.log(`  Would write: ${mcpPath}`);
  } else {
    await fs.writeFile(mcpPath, generateMcpToolsGuide(), "utf-8");
  }
}

// A static, correctness-focused reference for the MCP tools agent-smith configures.
// Serena gets the most detail because its API is the easiest to call incorrectly.
function generateMcpToolsGuide(): string {
  return `# MCP Tools — Usage Rules

Binding reference for calling the MCP servers agent-smith configures. Skills and commands
assume these exact tool names and signatures. **Only call tools that exist here.**

## Serena (LSP-backed symbol navigation & editing)

**Handshake (once per session):** call \`mcp__serena__check_onboarding_performed\` before any
other Serena call. If Serena tools are deferred/unloaded, load them via tool-search first.
**Serena line numbers are 0-based.**

### Discovery
- \`mcp__serena__get_symbols_overview(relative_path)\` — symbols in a file. Start here.
- \`mcp__serena__find_symbol(name_path_pattern, [relative_path], [depth], [include_body])\` —
  find a symbol. **Name paths use \`/\`, not \`.\`** → \`"ClassName/method"\`, not \`"ClassName.method"\`.
  Use \`depth=1\` to list a class's methods; \`include_body=true\` to read a symbol's source.
- \`mcp__serena__find_referencing_symbols(name_path, relative_path)\` — all call sites.
  **Both arguments are required.**

### Editing (use these, NOT the built-in Edit, for code discovered via Serena)
- \`mcp__serena__replace_symbol_body(name_path, relative_path, body)\` — rewrite a whole symbol.
- \`mcp__serena__insert_after_symbol\` / \`insert_before_symbol(name_path, relative_path, body)\`.
- \`mcp__serena__replace_content(relative_path, ...)\` — regex/string edit for a few lines.
- \`mcp__serena__rename_symbol(...)\` — rename across references.

### Tools that DO NOT exist (never call these)
- \`find_implementations\` → instead use \`find_referencing_symbols\` on the base symbol.
- \`get_diagnostics_for_file\` → instead run the project's type-check / test gate to catch errors.

## gitnexus (code graph)
Impact analysis, callers, route maps, blast radius. Use before/after changing public symbols.
If the index is stale, run \`npx gitnexus analyze\`.

## git-memory (history)
Why code changed: commit history, bug-fix history, file timelines.

## sentrux (architectural quality gate)
\`sentrux check .\` (rule violations) and \`sentrux gate .\` (regression vs baseline) before committing.

## obsidian / playwright / chrome-devtools
Documentation vault writes; live browser driving for screenshots; deep page inspection — used by docs skills.
`;
}

function generateBackendArchitecture(vars: TemplateVariables): string {
  const isPython = vars.BACKEND_LANG.toLowerCase().includes("python");
  const isDjango = vars.BACKEND_FRAMEWORK.toLowerCase().includes("django");
  const isTypeScript = vars.BACKEND_LANG.toLowerCase().includes("typescript");

  let doc = `# Backend Architecture — ${vars.PROJECT_NAME}

Binding rules for all backend work. Referenced by backend, test, PR review, and documentation commands. Violations are PR blockers.

## Stack

- ${vars.BACKEND_LANG} + ${vars.BACKEND_FRAMEWORK_DETAIL}
- Database: ${vars.DB_ENGINE} (${vars.ORM})
- Auth: ${vars.AUTH_METHOD}
- Imports: ${vars.IMPORT_STYLE}

---

## Project Structure

\`\`\`
${vars.BACKEND_DIR}/
├── views/          # HTTP adapters — parse request, call service, return response
├── services/       # Business logic — returns data, raises typed exceptions
├── repositories/   # Data access — all ORM/DB calls live here
├── models/         # Data models / entities
├── serializers/    # Request/response serialization
├── urls/           # Route definitions
└── tests/          # Unit + integration tests
\`\`\`

---

## Architecture Rules

`;

  if (isPython && isDjango) {
    doc += `### views.py — HTTP primary adapter

- Parse the request (deserialize, validate, extract query params).
- Call one service method per action.
- Construct and return Response — no business logic, no ORM, no adapter calls.

### services.py — business logic only

- No HTTP objects, no Response returns, no request passed in.
- Return plain dict/list/model instance.
- Raise typed exceptions for error paths.
- Never import rest_framework.response.Response.

### repositories.py — data access only

- All ORM/DB calls live here, nowhere else.
- No business logic, no HTTP objects.

`;
  }

  if (isTypeScript) {
    doc += `### Controller layer

- Parse request, validate input, call service.
- Return HTTP response — no business logic.

### Service layer

- Business logic only.
- Return typed results.
- Throw typed errors for failure paths.

### Repository / Data access layer

- All DB queries live here.
- Never import HTTP objects.

`;
  }

  // Role enforcement
  if (vars.ROLE_SYSTEM !== "none") {
    doc += `## Role Enforcement

${vars.ROLE_SYSTEM}

Valid roles: ${vars.ROLE_VALID_VALUES}

Every endpoint must be protected. Undecorated endpoints must deny by default (fail-closed).

`;
  }

  // Logging
  if (vars.LOGGING_PATTERN === "structured") {
    doc += `## Logging

All logger calls must include canonical keys: ${vars.LOGGING_CANONICAL_KEYS}

\`\`\`python
logger.info("event_name", extra={
    "trace_id": trace_id,
    "span_id": span_id,
    "user_id": user_id,
    "entity_id": entity_id,
    "action": "event_name",
})
\`\`\`

`;
  }

  // Pre-push gates — use the computed gate string
  const gates = vars.PRE_PUSH_GATES !== "none" ? vars.PRE_PUSH_GATES.split(" + ").map((g: string) => g).join("\n") : "# No automated gates configured";
  doc += `## Pre-push CI Gates

Run these from the project root before every push:

\`\`\`bash
${gates}
\`\`\`

`;

  doc += `---
*Generated by agent-smith — customize as needed.*
`;

  return doc;
}

function generateFrontendArchitecture(vars: TemplateVariables): string {
  let doc = `# Frontend Architecture — ${vars.PROJECT_NAME}

Binding rules for all frontend work. Referenced by frontend, test, PR review, and documentation commands. Violations are PR blockers.

## Stack

- ${vars.FRONTEND_FRAMEWORK}
- UI Library: ${vars.FRONTEND_UI_LIBRARY}
- Language: ${vars.FRONTEND_TYPE_CHECK_CMD ? "TypeScript" : "JavaScript"}
- Dev server: \`${vars.FRONTEND_DEV_SERVER_CMD}\`

---

## Project Structure

\`\`\`
${vars.FRONTEND_DIR}/src/
├── views/          # Route-level pages
├── components/     # Reusable UI components
├── stores/         # State management
├── api/            # HTTP client wrappers
├── composables/    # Shared composition functions
├── router/         # Route definitions + guards
├── styles/         # Global styles
├── locales/        # i18n translation files
└── types/          # Shared TypeScript interfaces
\`\`\`

---

## Component Rules

- All components use the project's canonical pattern.
- Props and emits must be typed.
- No hardcoded strings in templates — use i18n keys.

## State Management

- Stores never call the backend directly — always through api/ functions.
- State, getters, and actions must be typed.

## API Layer

- All HTTP calls go through the shared HTTP client.
- Never use raw fetch/axios outside the API layer.
- Every API function must have explicit request/response interfaces.
- Handle 401 → refresh/redirect; 403 → show error.

## Design System

- Use the UI library's components for all layout, forms, tables, dialogs.
- No custom CSS that duplicates library utilities.
- Reusable primitives in components/common/ — reuse before writing new ones.

## Verification Gates

\`\`\`bash
cd ${vars.FRONTEND_DIR} && ${vars.FRONTEND_TYPE_CHECK_CMD}
cd ${vars.FRONTEND_DIR} && ${vars.FRONTEND_LINT_CMD}
\`\`\`

---
*Generated by agent-smith — customize as needed.*
`;

  return doc;
}
