// Architecture writer — generates architecture docs from detected patterns
import path from "node:path";
import fs from "fs-extra";
import { resolveTemplate } from "../shared/templates.js";
import type { TemplateVariables } from "../shared/types.js";

export async function writeArchitectureDocs(
  targetDir: string,
  vars: TemplateVariables,
  dryRun: boolean = false,
): Promise<void> {
  const archDir = path.join(targetDir, "docs", "architecture");
  if (!dryRun) {
    fs.ensureDirSync(archDir);
  }

  // Generate backend architecture doc
  const backendDoc = generateBackendArchitecture(vars);
  const backendPath = path.join(archDir, "backend-architecture.md");
  if (dryRun) {
    console.log(`  Would write: ${backendPath}`);
  } else {
    await fs.writeFile(backendPath, backendDoc, "utf-8");
  }

  // Generate frontend architecture doc
  const frontendDoc = generateFrontendArchitecture(vars);
  const frontendPath = path.join(archDir, "frontend-architecture.md");
  if (dryRun) {
    console.log(`  Would write: ${frontendPath}`);
  } else {
    await fs.writeFile(frontendPath, frontendDoc, "utf-8");
  }
}

function generateBackendArchitecture(vars: TemplateVariables): string {
  const isPython = vars.BACKEND_LANG.toLowerCase().includes("python");
  const isDjango = vars.BACKEND_FRAMEWORK.toLowerCase().includes("django");
  const isTypeScript = vars.BACKEND_LANG.toLowerCase().includes("typescript");

  let doc = `# Backend Architecture — ${vars.PROJECT_NAME}

Binding rules for all backend work. Referenced by backend, test, PR review, and documentation commands. Violations are PR blockers.

## Stack

- ${vars.BACKEND_LANG} + ${vars.BACKEND_FRAMEWORK_DETAIL}
- Database: ${vars.DB_ENGINE} (${vars.ORM})
- Auth: ${vars.AUTH_METHOD}
- Imports: ${vars.IMPORT_STYLE}

---

## Project Structure

\`\`\`
${vars.BACKEND_DIR}/
├── views/          # HTTP adapters — parse request, call service, return response
├── services/       # Business logic — returns data, raises typed exceptions
├── repositories/   # Data access — all ORM/DB calls live here
├── models/         # Data models / entities
├── serializers/    # Request/response serialization
├── urls/           # Route definitions
└── tests/          # Unit + integration tests
\`\`\`

---

## Architecture Rules

`;

  if (isPython && isDjango) {
    doc += `### views.py — HTTP primary adapter

- Parse the request (deserialize, validate, extract query params).
- Call one service method per action.
- Construct and return Response — no business logic, no ORM, no adapter calls.

### services.py — business logic only

- No HTTP objects, no Response returns, no request passed in.
- Return plain dict/list/model instance.
- Raise typed exceptions for error paths.
- Never import rest_framework.response.Response.

### repositories.py — data access only

- All ORM/DB calls live here, nowhere else.
- No business logic, no HTTP objects.

`;
  }

  if (isTypeScript) {
    doc += `### Controller layer

- Parse request, validate input, call service.
- Return HTTP response — no business logic.

### Service layer

- Business logic only.
- Return typed results.
- Throw typed errors for failure paths.

### Repository / Data access layer

- All DB queries live here.
- Never import HTTP objects.

`;
  }

  // Role enforcement
  if (vars.ROLE_SYSTEM !== "none") {
    doc += `## Role Enforcement

${vars.ROLE_SYSTEM}

Valid roles: ${vars.ROLE_VALID_VALUES}

Every endpoint must be protected. Undecorated endpoints must deny by default (fail-closed).

`;
  }

  // Logging
  if (vars.LOGGING_PATTERN === "structured") {
    doc += `## Logging

All logger calls must include canonical keys: ${vars.LOGGING_CANONICAL_KEYS}

\`\`\`python
logger.info("event_name", extra={
    "trace_id": trace_id,
    "span_id": span_id,
    "user_id": user_id,
    "entity_id": entity_id,
    "action": "event_name",
})
\`\`\`

`;
  }

  // Pre-push gates
  doc += `## Pre-push CI Gates

Run from ${vars.BACKEND_DIR}/ before every push:

\`\`\`bash
${vars.BACKEND_LINT_CMD}
${vars.BACKEND_TYPE_CHECK_CMD}
${vars.BACKEND_TEST_CMD}
\`\`\`

`;

  doc += `---
*Generated by agent-smith — customize as needed.*
`;

  return doc;
}

function generateFrontendArchitecture(vars: TemplateVariables): string {
  let doc = `# Frontend Architecture — ${vars.PROJECT_NAME}

Binding rules for all frontend work. Referenced by frontend, test, PR review, and documentation commands. Violations are PR blockers.

## Stack

- ${vars.FRONTEND_FRAMEWORK}
- UI Library: ${vars.FRONTEND_UI_LIBRARY}
- Language: ${vars.FRONTEND_TYPE_CHECK_CMD ? "TypeScript" : "JavaScript"}
- Dev server: \`${vars.FRONTEND_DEV_SERVER_CMD}\`

---

## Project Structure

\`\`\`
${vars.FRONTEND_DIR}/src/
├── views/          # Route-level pages
├── components/     # Reusable UI components
├── stores/         # State management
├── api/            # HTTP client wrappers
├── composables/    # Shared composition functions
├── router/         # Route definitions + guards
├── styles/         # Global styles
├── locales/        # i18n translation files
└── types/          # Shared TypeScript interfaces
\`\`\`

---

## Component Rules

- All components use the project's canonical pattern.
- Props and emits must be typed.
- No hardcoded strings in templates — use i18n keys.

## State Management

- Stores never call the backend directly — always through api/ functions.
- State, getters, and actions must be typed.

## API Layer

- All HTTP calls go through the shared HTTP client.
- Never use raw fetch/axios outside the API layer.
- Every API function must have explicit request/response interfaces.
- Handle 401 → refresh/redirect; 403 → show error.

## Design System

- Use the UI library's components for all layout, forms, tables, dialogs.
- No custom CSS that duplicates library utilities.
- Reusable primitives in components/common/ — reuse before writing new ones.

## Verification Gates

\`\`\`bash
cd ${vars.FRONTEND_DIR} && ${vars.FRONTEND_TYPE_CHECK_CMD}
cd ${vars.FRONTEND_DIR} && ${vars.FRONTEND_LINT_CMD}
\`\`\`

---
*Generated by agent-smith — customize as needed.*
`;

  return doc;
}
